[build-system]
# Synchronise with `setup_requirements` in `setup.cfg`
requires = [
    "setuptools",
    "wheel",
    "cffi",
    "conan",
    "importlib_resources",
]
build-backend = "setuptools.build_meta"
