version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip3 install build
      - run: python3 -m build --sdist
      - run: pip3 install dist/webp-*.tar.gz
      - run: pip3 install pytest==5.4.3
      - run: pytest tests/
